/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'BensDell' at '11/30/15 11:52 PM' with Gradle 2.6
 *
 * @author BensDell, @date 11/30/15 11:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
